# This is a basic workflow to help you get started with Actions

name: Sync with test servers

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup SSH Keys and known_hosts
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add - <<< "${{ secrets.DEPLOY_KEY }}"

    # "2244 pterodactyl@eu9.potato.tf:/"
    # Runs a set of commands using the runners shell
      - name: Sync with game servers
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          rsync -a --chmod=777 --mkpath -e "ssh -o StrictHostKeyChecking=no" ./scripts/vscripts/* pterodactyl@storage.potato.tf:/mnt/archival/testing_uploads_current/scripts/vscripts/
          rsync -a --chmod=777 --mkpath -e "ssh -o StrictHostKeyChecking=no" ./mvm_slick_v4a_tankextensions.pop pterodactyl@storage.potato.tf:/mnt/archival/testing_uploads_current/scripts/population/
          rsync -a --chmod=777 --mkpath -e "ssh -o StrictHostKeyChecking=no" ./assets/*/models/* pterodactyl@storage.potato.tf:/mnt/archival/testing_uploads_current/models/
          rsync -a --chmod=777 --mkpath -e "ssh -o StrictHostKeyChecking=no" ./assets/*/materials/* pterodactyl@storage.potato.tf:/mnt/archival/testing_uploads_current/materials/
          curl https://testing.potato.tf/forceupdate.php?serverkey=23049785
